version: 2
updates:
  # Enable npm dependency updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    # Keep pull requests to a manageable number
    open-pull-requests-limit: 10
    # Grouping strategy for minor and patch updates
    groups:
      # Group all development dependencies together
      development-dependencies:
        patterns:
          - "@types/*"
          - "@jest/*"
          - "jest"
          - "ts-jest"
          - "typescript"
          - "tsx"
        update-types:
          - "minor"
          - "patch"
      # Group production dependencies by update type
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "@jest/*"
          - "jest"
          - "ts-jest"
          - "typescript"
          - "tsx"
        update-types:
          - "patch"
    # Semantic versioning strategy
    versioning-strategy: increase
    # Commit message configuration
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Labels for created PRs
    labels:
      - "dependencies"
      - "automated"
    # Review settings
    reviewers:
      - "jordan-huffman"
    # Security updates separate from version updates
    allow:
      - dependency-type: "all"
    # Pull request configuration
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"

  # Enable GitHub Actions dependency updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    reviewers:
      - "jordan-huffman"
